---
- name: Setup centralRouter
  hosts: centralRouter
  become: yes
  tasks:
    - name: Install necessary packages
      yum:
        name:
          - iproute
          - iputils
        state: present

    - name: Configure centralRouter interfaces
      command: ip addr add {{ item.address }} dev {{ item.interface }}
      loop:
        - { address: "192.168.0.2/28", interface: "eth1" }
        - { address: "192.168.2.2/26", interface: "eth2" }
        - { address: "192.168.1.2/25", interface: "eth3" }

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes

    - name: Setup static routes
      command: ip route add 192.168.2.0/26 via 192.168.0.1