---
- name: Setup centralServer
  hosts: centralServer
  become: yes
  tasks:
    - name: Install necessary packages
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Configure network settings
      command: ip addr add 192.168.0.4/28 dev eth0